sudo: enabled
language: python
python:
  - 3.6
notifications: 
  slack: "cryptobotgroupe:vYDDCLRne52jPGVtN6cMiUkb"
  email: false
install:
  - ./docs/install/install-ta-lib.sh
  - pip install tox-travis coveralls
  - python -m pip install -r requirements.txt
script:
  - pytest tests/ --cov coveralls


