sudo: enabled
language: python
python:
  - 3.6
notifications: 
  slack: "cryptobotgroupe:vYDDCLRne52jPGVtN6cMiUkb"
  email: false
install:
  - ./docs/install/install-ta-lib.sh
  - python -m pip install python-coveralls
  - python -m pip install -r requirements.txt
script: pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing tests/
after_success:
  - coveralls


