sudo: enabled
language: python
python:
  - 3.6
notifications: 
  slack: "cryptobotgroupe:vYDDCLRne52jPGVtN6cMiUkb"
  email: false
install:
  - ./docs/install/install-ta-lib.sh
  - python -m pip install -r requirements.txt
  - python -m pip install -r dev_requirements.txt
script:
  - pytest --cov-report term --cov=. tests/unit_tests/


